#!/usr/bin/env bash
# cmd_hook.sh — keep the in-repo graph in sync with commits.
#
# ibis's graph lives IN the repo (.ibis/GRAPH.dot), so a commit that closes a
# node's todo= CAN — and should — update the graph in the SAME commit. (A
# centralized graph, like a separate coordination repo, can't do this: the work
# and the annotation are in different repos, so shipped work silently leaves the
# graph stale and other workers read it as still-open.)
#
# This installs a `commit-msg` hook that fires when a commit uses completion
# language but doesn't stage .ibis/GRAPH.dot while open todo= items exist.
# Default: warn. IBIS_HOOK_STRICT=1: block.

COMPLETION_RE='\b(done|closed?|closes|fix(ed|es)?|resolv(e|ed|es)|ship(ped)?|complete[ds]?|scrub(bed|s)?|finish(ed)?|mark(ed)? done)\b'

ibis_hook() {
  local sub="${1:-help}"; shift || true
  case "$sub" in
    install)      _hook_install;;
    uninstall)    _hook_uninstall;;
    check)        _hook_check "$@";;
    post-commit)  _hook_post_commit;;
    pre-commit)   _hook_pre_commit;;
    guard)        _hook_guard "$@";;
    *) echo "usage: ibis hook <install|uninstall|guard>"; return 0;;
  esac
}

_hook_path() {
  set_paths
  local gd; gd="$(git -C "$REPO_ROOT" rev-parse --git-dir 2>/dev/null)" || die "not a git repo"
  mkdir -p "$gd/hooks"
  printf '%s/hooks/commit-msg\n' "$gd"
}

_hook_install() {
  set_paths; require_init
  local gd; gd="$(git -C "$REPO_ROOT" rev-parse --git-dir 2>/dev/null)" || die "not a git repo"

  # Hooks live IN the repo (.ibis/githooks) and are activated with
  # core.hooksPath — not copied into .git/hooks, which git does not track.
  # An untracked hook is a protection that silently disappears on a fresh
  # clone while the docs still claim it is active; its removal also never
  # shows up in a diff. Tracked hooks fail visibly instead.
  local hd="$IBIS_DIR/githooks"
  mkdir -p "$hd"

  local ibis_bin="$IBIS_HOME/bin/ibis"

  cat > "$hd/pre-commit" <<EOF
#!/usr/bin/env bash
# Generated by: ibis hook install — tracked, activated via core.hooksPath.
# Emergency bypass: git commit --no-verify
exec "$ibis_bin" hook pre-commit
EOF

  cat > "$hd/commit-msg" <<EOF
#!/usr/bin/env bash
# Generated by: ibis hook install
exec "$ibis_bin" hook check "\$1"
EOF

  cat > "$hd/post-commit" <<EOF
#!/usr/bin/env bash
# Generated by: ibis hook install
"$ibis_bin" hook post-commit
EOF

  chmod +x "$hd"/pre-commit "$hd"/commit-msg "$hd"/post-commit
  git -C "$REPO_ROOT" config core.hooksPath "${hd#$REPO_ROOT/}"

  ok "installed tracked hooks → ${hd#$REPO_ROOT/}"
  echo "    core.hooksPath = $(git -C "$REPO_ROOT" config core.hooksPath)"
  echo "    commit these so a fresh clone keeps them:"
  echo "      git add ${hd#$REPO_ROOT/} && git commit -m 'ibis: track git hooks'"
  echo "    block instead of warn:  export IBIS_HOOK_STRICT=1"

  # Legacy: remove untracked copies so there is exactly one source of truth.
  local f
  for f in pre-commit commit-msg post-commit; do
    if [[ -f "$gd/hooks/$f" ]] && grep -q 'ibis' "$gd/hooks/$f" 2>/dev/null; then
      rm -f "$gd/hooks/$f"
      warn "removed untracked $gd/hooks/$f (superseded by core.hooksPath)"
    fi
  done
}

_hook_uninstall() {
  local gd; gd="$(git -C "$REPO_ROOT" rev-parse --git-dir 2>/dev/null)" || die "not a git repo"
  local hook; hook="$(_hook_path)"
  if [[ -f "$hook" ]] && grep -q 'hook check' "$hook"; then
    rm -f "$hook"; ok "removed $hook"
  else
    warn "no ibis commit-msg hook installed"
  fi
  local pc="$gd/hooks/post-commit"
  if [[ -f "$pc" ]] && grep -q 'hook post-commit' "$pc"; then
    rm -f "$pc"; ok "removed $pc"
  else
    warn "no ibis post-commit hook installed"
  fi
  local pre="$gd/hooks/pre-commit"
  if [[ -f "$pre" ]] && grep -q 'hook pre-commit' "$pre"; then
    rm -f "$pre"; ok "removed $pre"
  fi
}

# _hook_check <commit-msg-file> — run by git. exit 0 = allow, 1 = block (strict).
# Two independent checks: graph-sync (closed a todo? stage the graph) and
# doc-coverage (touched a cover= file? a node must track it via doc=).
_hook_check() {
  set_paths
  [[ -f "$GRAPH" ]] || return 0
  local msgfile="${1:-}" msg="" staged
  [[ -f "$msgfile" ]] && msg="$(grep -v '^#' "$msgfile" 2>/dev/null || true)"
  staged="$(git -C "$REPO_ROOT" diff --cached --name-only 2>/dev/null || true)"
  local rc=0
  _hook_graph_sync   || rc=1
  _hook_doc_coverage || rc=1
  _hook_doc_drift    || rc=1
  return $rc
}

# Closed work but didn't stage .ibis/GRAPH.dot while open todos exist → drift.
_hook_graph_sync() {
  echo "$staged" | grep -q '\.ibis/GRAPH\.dot$' && return 0
  grep -q 'todo="' "$GRAPH" 2>/dev/null || return 0           # no open todos
  echo "$msg" | grep -qiE "$COMPLETION_RE" || return 0        # not completion language
  cat >&2 <<EOF

⚠ ibis GRAPH-SYNC: this commit reads like it closes work, but it doesn't stage
  .ibis/GRAPH.dot — and the graph still has open todo= items. Other workers read
  the graph, not your commit. Clear the todo you finished in THIS commit:
    \$EDITOR .ibis/GRAPH.dot && git add .ibis/GRAPH.dot
  See open todos:  grep -n 'todo="' .ibis/GRAPH.dot
EOF
  [[ -n "${IBIS_HOOK_STRICT:-}" ]] && { echo "  IBIS_HOOK_STRICT=1 → blocking." >&2; return 1; }
  return 0
}

# Files matching .ibis/config cover= globs must be referenced by a node's doc=,
# so a stale string in them is caught by that node's test= instead of by a human.
# (The portable form of the hub's pre-commit-graph-doc-check.)
_hook_doc_coverage() {
  local cover; cover="$(config_get cover)"
  [[ -z "$cover" ]] && return 0
  local docs; docs="$(grep -oE 'doc[0-9]*="[^"]+"' "$GRAPH" | sed 's/^doc[0-9]*="//;s/"$//' | sort -u)"
  local missing=() f d pat matched ok
  while IFS= read -r f; do
    [[ -z "$f" ]] && continue
    matched=0; local IFS=','; local pats=($cover); unset IFS
    for pat in "${pats[@]}"; do
      pat="$(echo "$pat" | xargs)"; [[ -z "$pat" ]] && continue
      case "$f" in $pat) matched=1; break;; esac
    done
    [[ $matched -eq 0 ]] && continue
    ok=0
    while IFS= read -r d; do
      [[ -z "$d" ]] && continue
      [[ "$f" == "$d" ]] && { ok=1; break; }
      [[ "$d" == */ && "$f" == "$d"* ]] && { ok=1; break; }
      [[ -d "$REPO_ROOT/$d" && "$f" == "$d/"* ]] && { ok=1; break; }
    done <<<"$docs"
    [[ $ok -eq 0 ]] && missing+=("$f")
  done <<<"$staged"
  [[ ${#missing[@]} -eq 0 ]] && return 0
  { echo ""
    echo "⚠ ibis DOC-COVERAGE: these touched files match cover= but no graph node"
    echo "  references them (doc=) — untracked, so no test= pin guards them:"
    printf '    - %s\n' "${missing[@]}"
    echo "  Add a node with doc= (and test=) for each."
  } >&2
  [[ -n "${IBIS_HOOK_STRICT:-}" ]] && { echo "  IBIS_HOOK_STRICT=1 → blocking." >&2; return 1; }
  return 0
}

# Commit uses fix/close language but no documentation file (.md) is staged.
# When you fix something, the doc should be updated in the same commit.
_hook_doc_drift() {
  echo "$msg" | grep -qiE "$COMPLETION_RE" || return 0
  echo "$staged" | grep -qiE '\.(md|rst|txt)$' && return 0
  local doc_dir="$IBIS_DIR/docs"
  [[ -d "$doc_dir" ]] || return 0
  local has_docs; has_docs="$(ls "$doc_dir"/*.md 2>/dev/null | head -1)"
  [[ -z "$has_docs" ]] && return 0
  cat >&2 <<EOF

⚠ ibis DOC-DRIFT: this commit reads like it closes or fixes work, but no
  documentation file (.md) is staged. If the fix changes behavior, update
  the relevant doc in .ibis/docs/ in this same commit.
  Staged files: $(echo "$staged" | tr '\n' ' ')
EOF
  [[ -n "${IBIS_HOOK_STRICT:-}" ]] && { echo "  IBIS_HOOK_STRICT=1 → blocking." >&2; return 1; }
  return 0
}

# _hook_post_commit — auto-notify with commit hash + subject + changed files.
# Runs after every commit via the post-commit hook.
_hook_post_commit() {
  set_paths
  [[ -d "$IBIS_DIR" ]] || return 0
  local hash subject files proj
  hash="$(git -C "$REPO_ROOT" rev-parse --short HEAD 2>/dev/null)" || return 0
  subject="$(git -C "$REPO_ROOT" log -1 --format='%s' 2>/dev/null)" || return 0
  files="$(git -C "$REPO_ROOT" diff-tree --no-commit-id --name-only -r HEAD 2>/dev/null | head -5)"
  proj="$(config_get name 2>/dev/null)"
  [[ -z "$proj" ]] && proj="$(basename "$REPO_ROOT")"
  local flist=""
  [[ -n "$files" ]] && flist=" | $(echo "$files" | tr '\n' ' ')"
  ibis_notify "[$proj] $hash $subject$flist" 2>/dev/null || true
}

# _hook_guard — block a commit that touches a node declaring invariant=.
# Always blocking (not warn-only): the whole point is that a design decision
# cannot be reverted by someone who never read it. Acknowledge with IBIS_ACK=1.
_hook_guard() {
  set_paths
  [[ -f "$GRAPH" ]] || return 0
  local guard="$IBIS_HOME/lib/graph_guard.py"
  [[ -f "$guard" ]] || return 0
  "${PYTHON:-python3}" "$guard" --graph "$GRAPH" "$@"
}

# _hook_pre_commit — design-invariant guard, then the notify-required gate.
# Blocks commit if no ibis notify was recorded in the last N minutes.
# Enable: require_notify=true in .ibis/config
# Configure window: notify_window=15 in .ibis/config (default 15 min)
_hook_pre_commit() {
  set_paths
  [[ -d "$IBIS_DIR" ]] || return 0

  # 1. Design invariants — always enforced, independent of any config flag.
  _hook_guard || return 1

  # 2. Notify gate — opt-in via require_notify=true in .ibis/config.
  local rn; rn="$(config_get require_notify)"
  [[ "$rn" == "true" ]] || return 0
  local window; window="$(config_get notify_window)"
  [[ -z "$window" ]] && window=15
  local cutoff notify_dir="$IBIS_DIR/.notify"
  cutoff=$(( $(date +%s) - window * 60 ))
  local found=0
  if [[ -d "$notify_dir" ]]; then
    local f
    for f in "$notify_dir"/*.pending "$notify_dir"/*.drained; do
      [[ -e "$f" ]] || continue
      local mtime
      if stat --version &>/dev/null; then
        mtime=$(stat -c '%Y' "$f" 2>/dev/null) || continue
      else
        mtime=$(stat -f '%m' "$f" 2>/dev/null) || continue
      fi
      if [[ "$mtime" -ge "$cutoff" ]]; then
        found=1; break
      fi
    done
  fi
  if [[ $found -eq 0 ]]; then
    cat >&2 <<EOF

⚠ ibis NOTIFY-REQUIRED: no ibis notify in the last ${window} minutes.
  Before committing, describe what you're about to do:
    ibis notify "what you changed"
  Then retry the commit.
  (Disable: set require_notify=false in .ibis/config)
EOF
    return 1
  fi
  return 0
}
